### ISSUE TITLE
About generate_program regular expression

### ISSUE THREAD

**Issue by suiyize** [iiis-ai/cumulative-reasoning#3]
I use gpt-3.5-turbo run the source code,when the tree structure iterates, After **generate_program** execution, the **out['next_step']** attribute will appear like '_Since the input consists of only two numbers, there are no possible forbidden steps. To obtain 24, we can use the following step: 20 - 4 = 16_'.Then the regular expression "[^0-9+\-*/.(),=\s]" will  matches unrelated strings，so that the next judgment statement jumps into **continue**，the correct branch 20 - 4 = 16 is ignored .
![image](https://github.com/iiis-ai/cumulative-reasoning/assets/71477998/9c84e0e6-822e-4c30-a252-6fb04a469daa)

**Comment by yjqqqaq** [comment]
Thank you for your question. The main reason we added special judge here is to prevent unknown format errors when calling the API. In fact, you'll find in the prompts of 'generate_program' that we expect 'Next Step' to be an equation composed solely of numbers and equals signs, which makes it more convenient for us to handle. When we use GPT-4 as the model, it is able to correctly understand our needs and almost never produces additional descriptive text that would cause this line of judgment to fail. So we added this judgment simply to avoid unexpected errors during the API execution of GPT-4. 

We guess the problem you encountered may be due to GPT-3.5-Turbo, which interprets the prompt in a slightly different way than GPT-4, resulting in unnecessary extra description words in the output. We need to point out that if the output format of the "Next Step" is uncertain and contains additional descriptive text, extracting the "Next Step" equation we need is a non-trivial task. Therefore, in such situations, we choose to ignore this API call and regenerate it.

We will take your question seriously, and in future updates, we will try to solve Game 24 using GPT-3.5-Turbo, and attempt to provide new prompts that are compatible with both GPT-3.5-Turbo and GPT-4.
